### ISSUE TITLE
Navigation Bar Dropping into Banner 

### ISSUE THREAD

**Issue by cbukovac** [GSA/fedramp-gov#57]
@wslack This was a problem we had during beta testing that Lance resolved. I'm not sure what your update to our header was last week, but could it of impacted the fix Lance put in place? 

<img width="1280" alt="screen shot 2018-02-07 at 12 01 06 pm" src="https://user-images.githubusercontent.com/25774107/35937362-fddb108a-0c13-11e8-9b2d-bf96de22668f.png">

**Comment by wslack** [comment]
@cbukovac I don't think so; the change we made was for the top header.

To find out, I would just reverse this commit in a new branch and see if that fixes it! https://github.com/GSA/fedramp-gov/pull/51/files

(if that is the issue, I would suggest making more code updates, since the Lance fix caused the site to break on mobile for android)

**Comment by cbukovac** [comment]
@wslack ok I'll bring in Margo or get Lance back to fix. Thanks

**Comment by wslack** [comment]
👍  we can investigate if if you want; we have the hours.

**Comment by cbukovac** [comment]
@margo29 knows how to fix it, but if she encounters problems we'll engage you/federalist. I'm leaving this issue open for now for my own reference.
